[snowflake]
account = "DIYLQGZ-LJA25310",
user = "LYSA.MOULTON@CONCORD.COM",
authenticator="externalbrowser",
warehouse='DEV_QUERY_DA_1',
database = "BUS_CORPORATE",
schema = "RIGHTS_OPTIMIZATION",
role='TM_COR_RIGHTS_OPTIMIZATION'

# optional: if you want to override defaults (not required since table is fully qualified)
database = "BUS_CORPORATE"
schema = "RIGHTS_OPTIMIZATION"

[youtube]
api_key = "AIzaSyABHR7J2mXg0kr1CEGVRe5ihw6M0bGHOig"
